apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  seed-initial-data: "True"
  event-bus-host: event-bus
  event-bus-user: rabbitmquser

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  carrental-database-sa-password: Y2FycmVudGFsRGF0YWJhc2VQYXNzd29yZDEyIUA=
  security-token-secret: UzBNMyBNNEcxQyBVTjFDMFJOUyBHM04zUjRUM0QgVEgxUyBTM0NSM1Q=
  admin-password: YWRtaW5wYXNzMTIh
  identity-service-connection-string: U2VydmVyPWNhcnJlbnRhbC1kYXRhYmFzZTtEYXRhYmFzZT1DYXJSZW50YWxJZGVudGl0eURhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPWNhcnJlbnRhbERhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  dealers-service-connection-string: U2VydmVyPWNhcnJlbnRhbC1kYXRhYmFzZTtEYXRhYmFzZT1DYXJSZW50YWxEZWFsZXJzRGF0YWJhc2U7VXNlciBJZD1zYTsgUGFzc3dvcmQ9Y2FycmVudGFsRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
  dealers-service-cron-jobs-connection-string: U2VydmVyPWNhcnJlbnRhbC1kYXRhYmFzZTtEYXRhYmFzZT1DYXJSZW50YWxEZWFsZXJzQ3JvbkpvYnNEYXRhYmFzZTtVc2VyIElkPXNhOyBQYXNzd29yZD1jYXJyZW50YWxEYXRhYmFzZVBhc3N3b3JkMTIhQDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  statistics-service-connection-string: U2VydmVyPWNhcnJlbnRhbC1kYXRhYmFzZTtEYXRhYmFzZT1DYXJSZW50YWxTdGF0aXN0aWNzRGF0YWJhc2U7VXNlciBJZD1zYTsgUGFzc3dvcmQ9Y2FycmVudGFsRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
  statistics-service-cron-jobs-connection-string: U2VydmVyPWNhcnJlbnRhbC1kYXRhYmFzZTtEYXRhYmFzZT1DYXJSZW50YWxTdGF0aXN0aWNzQ3JvbkpvYnNEYXRhYmFzZTtVc2VyIElkPXNhOyBQYXNzd29yZD1jYXJyZW50YWxEYXRhYmFzZVBhc3N3b3JkMTIhQDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==
  